import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/helpers/sideBar/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" flex flex-row w-full h-screen">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
