import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/helpers/sideBar/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className+" bg-core-secBg"}>
        <main className=" flex flex-row w-full max-w-[1440px] m-auto bg-core-secBg h-screen max-sm:max-h-screen max-sm:overflow-hidden max-sm:flex-col-reverse">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
